---
version: "3"

includes:
  mdox: ./Taskfile.mdox.yml

vars:
  goversion:
    sh: go env GOVERSION
  toolchain: '{{.goversion}}+auto'

tasks:
  default:
    desc: "Run the playground server"
    cmds:
      - task: fmt
      - task: lint
      - go build -o bin/ ./cmd/yamlexpr

  fmt:
    desc: "Format code and tidy dependencies"
    cmds:
      - goimports -w -local $(go list .) .
      - goimports-reviser -set-alias -format -imports-order "std,blanked,general,company,project" ./...
      - gofumpt -w .
      - go mod tidy

  fmt:docs:
    desc: "Format docs"
    cmds:
      - task: mdox:fmt

  lint:
    desc: "Lint codebase"
    cmds:
      - task: fmt
      - task: lint:tools:golangci-lint
      - task: lint:godoc

  lint:tools:golangci-lint:
    cmd: golangci-lint run --fix ./...

  lint:godoc:
    desc: "Lint godoc comments"
    cmds:
      - schema-gen extract --pretty-json
      - schema-gen lint --summary

  test:
    desc: "Run tests and collect coverage"
    deps:
      - fmt
    env:
      GOTOOLCHAIN: '{{.toolchain}}'
    cmds:
      - go test -failfast -count=1 -cover -coverpkg=./... -coverprofile=pkg.cov ./...

  cover:
    desc: "Show source coverage"
    cmds:
      - go-fsck extract . --include-sources
      - go-fsck docs > docs/api.md
      - go tool cover -func=pkg.cov | summary coverfunc --json > pkg.cov.json
      - go-fsck extract --pretty-json ./...
      - go-fsck coverage -c pkg.cov.json -o go-fsck.json
      - go-fsck coverage --template=docs/testing-coverage.md.tpl -v > docs/testing-coverage.md
      - perl -pi -e 's/github.com\/titpetric/titpetric/g' docs/testing-coverage.md
      - task: fmt:docs

  uncover:
    desc: "Show uncovered source"
    cmd: uncover pkg.cov

  render:
    desc: "Render a vuego template"
    cmds:
      - go run ./cmd/vuego testdata/pages/forecast.vuego testdata/json/forecast.json

  bench:
    desc: "Run benchmarks with multiple CPU configurations"
    deps:
      - fmt
    cmds:
      - go test -bench=. -benchmem -cpu 1,2,4 ./...
